on:
  push:
    tags:
      - "v*"

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Download binaries"
        run: |
          chmod +x ./index.sh
          sh ./index.sh

      - name: "Create release"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ffmpeg/darwin/ffmpeg
            ffmpeg/windows-x86/ffmpeg.exe
            ffmpeg/windows-x64/ffmpeg.exe

